### PR TITLE
Resolved security vulnerability

### PR DESCRIPTION
**Pull request by akoniar**
https://github.com/rhoar-qe/boosters-e2e-tests/network/alert/package-lock.json/adm-zip/open

### CODE REVIEW

**Comment by akoniar** [comment]
@Ladicek, thanks

**Comment by Ladicek** [comment]
I wonder what's rhoar-bot doing...

**Comment by Ladicek** [comment]
Ah, the Jenkins agent images were somehow lost. Rebuilding them now.

**Comment by Ladicek** [comment]
Yay :-)

**Comment by akoniar** [comment]
@Ladicek I also thought about what rhoar-bot was doing. Thank you for you look at :-)

**Pull request merged**
