### PR TITLE
Updated vulnerable dependency

### PR DESCRIPTION
**Pull request by mocenas**

### CODE REVIEW

**Comment by Ladicek** [comment]
I don't quite understand why there are 5 commits?

**Comment by mocenas** [comment]
I also don't understand it. I send these additional commits for PR a while ago and I think that they were accepted.

**Comment by Ladicek** [comment]
Then you didn't make this PR on top of latest master branch, or something like that.

**Comment by mocenas** [comment]
@Ladicek Thats possible, should it try to close it reopen again, or is it OK in this state?

**Comment by Ladicek** [comment]
You can force-push a fixed branch.

**Comment by mocenas** [comment]
Hmm I look to the commit log, and it seems that these commits are not present in the main repo. Although their result is in the files. That's strange. I thing I will just remove these commits and do the PR again.

**Comment by Ladicek** [comment]
I think I probably squashed those commits when merging, because who wants a commit "reworked commet" in their history? ;-)

**Pull request closed without merging**
